app/models.py
from . import db
from flask_login import UserMixin
from app import login_manager
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    
class User(UserMixin,db.Model):
    """
    Class I will use to create users
    """
    __tablename__ = "users"
    id = db.Column(db.Integer,primary_key = True)
    full_name = db.Column(db.String)
    username = db.Column(db.String)
    email = db.Column(db.String)
    bio = db.Column(db.String)
    image = db.Column(db.String)
    posts = db.relationship("Post", backref = "user", lazy = "dynamic")
    user_pass = db.Column(db.String)

    def save_user(self):
        db.session.add(self)
        db.session.commit()
        
    @property
    def password(self):
        raise AttributeError("Gerrarahia")

    @password.setter
    def password(self,password):
        self.user_pass = generate_password_hash(password)

    def verify_pass(self,password):
        return check_password_hash(self.user_pass, password)
    


class Post(db.Model):
    __tablename__ = "posts"
    id  = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    content = db.Column(db.String)
    time = db.Column(db.String)
    image = db.Column(db.String)
    comments = db.relationship("Comment",backref = "post", lazy = "dynamic")
    def get_post_comments(self):
        return Comment.query.filter_by(post_id = self.id)

    def save_post(self):
        db.session.add(self)
        db.session.commit()

class Comment(db.Model):
    __tablename__ = "comments"
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String)
    title = db.Column(db.String)
    content = db.Column(db.String)
    post_id = db.Column(db.Integer, db.ForeignKey("posts.id"))
    time = db.Column(db.String)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

class Subscriber(db.Model):
    __tablename__ = "subscribers"
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String)

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class AddPostForm(FlaskForm):
    title = StringField("Title", validators = [Required()])
    content = TextAreaField("Post", validators = [Required()])
    submit = SubmitField("Add Post")

class SubscribeForm(FlaskForm):
    email = StringField("Enter email", validators = [Required()])
    submit = SubmitField("Subscribe")

class AddComment(FlaskForm):
    name = StringField("Name", validators = [Required()])
    comment = TextAreaField("Comment", validators = [Required()])
    submit = SubmitField("Comment")
    
class EditBio(FlaskForm):
    bio = StringField("Bio")
    submit = SubmitField("Update")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,IMAGES,configure_uploads

login_manager = LoginManager()
login_manager.session_protection = "strong"
login_manager.login_view = "auth.login"

db = SQLAlchemy()
bootstrap = Bootstrap()
photos = UploadSet("photos",IMAGES)
mail = Mail()

def create_app(config_name):

    # create instance of Flask
    app = Flask(__name__)

    # add configurations
    app.config.from_object(config_options[config_name])

    # initialize extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    #register blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    #config uploads
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views,error

app/main/views.py
from . import main
from flask_login import current_user, login_required
from .forms import AddPostForm,SubscribeForm,AddComment,EditBio
from ..models import Post,User,Comment,Subscriber
from flask import redirect,url_for,render_template,flash,request
from .. import db,photos
from datetime import datetime
from app.email import create_mail

@main.route("/", methods = ["GET","POST"])
def index():
    form = SubscribeForm()
    if form.validate_on_submit():
        email = form.email.data
        new_subscriber = Subscriber(email = email)
        db.session.add(new_subscriber)
        db.session.commit()
        flash("Thank You for subscribing!")
        return redirect(url_for("main.index"))
    posts = Post.query.order_by(Post.time.desc())
    title = "Home"
    return render_template("index.html",posts = posts,form = form,title = title)

@main.route("/add/post/",methods = ["GET","POST"])
@login_required
def add_post():
    form = AddPostForm()
    title = "Add Post"


    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        posted = str(datetime.now())
        print(posted)
        if "photo" in request.files:
            pic = photos.save(request.files["photo"])
            file_path = f"photos/{pic}"
            image = file_path
        new_post = Post(title = title, content = content, user = current_user,image = image,time = posted)
        new_post.save_post()
        subscribers = Subscriber.query.all()
        emails = []
        
        return redirect(url_for('main.index'))

    return render_template("add_pitch.html",form = form,title = title)

@main.route("/post/<int:id>",methods = ["GET","POST"])
def post_page(id):
    post = Post.query.filter_by(id = id).first()
    title = post.title
    form = AddComment()
    if form.validate_on_submit():
        name = form.name.data
        content = form.comment.data
        new_comment = Comment(name = name, content = content, post = post)
        new_comment.save_comment()
        return redirect(url_for('main.post_page', id = post.id))
    comments = Comment.query.filter_by(post_id = post.id)
    title = post.title
    return render_template("post.html", title = title, post = post,form = form,comments = comments)

@main.route("/delete/<id>")
def delete(id):
    post = Post.query.filter_by(id = id).first()
    user_id = post.user_id
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('main.profile', id = user_id))

@main.route("/delete/comment/<id>")
def delete_comment(id):
    comment = Comment.query.filter_by(id = id).first()
    post_id = comment.post.id
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("main.post_page", id = post_id))

@main.route("/profile/<id>")
def profile(id):
    user = User.query.filter_by(id = id).first()
    posts = Post.query.filter_by(user_id = user.id).order_by(Post.time.desc())
    title = user.full_name
    return render_template("profile.html", user = user,posts = posts, title = title)

@main.route("/<user_id>/profile/edit",methods = ["GET","POST"])
@login_required
def update_profile(user_id):
    title = "Edit Profile"
    user = User.query.filter_by(id = user_id).first()
    form = EditBio()

    if form.validate_on_submit():
        bio = form.bio.data
        user.bio = bio
        db.session.commit() 
        return redirect(url_for('main.profile',id = user.id)) 
    return render_template("update_profile.html",form = form,title = title)

@main.route("/pic/<user_id>/update", methods = ["POST"])
@login_required
def update_pic(user_id):
    user = User.query.filter_by(id = user_id).first()
    title = "Edit Profile"
    if "profile-pic" in request.files:
        pic = photos.save(request.files["profile-pic"])
        file_path = f"photos/{pic}"
        user.image = file_path
        db.session.commit()
    return redirect(url_for("main.profile", id = user.id))

app/templates/add_pitch.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="../static/css/index.css">
{% endblock %}

{% block content%}
    <div class="container">
        <form class="form-group" method="post" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            {{form.title.label}}
            {{form.title(class = "form-control",style="margin-bottom: 10px;")}}
            {{form.content.label}}
            {{form.content(class = "form-control", style="margin-bottom: 15px;")}}
            <input type="file" name="photo" id="" class="form-control" style="margin-bottom:15px" required>
            {{form.submit(class = "btn btn-sm btn-info")}}
        </form>
    </div>
{% endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html' %}



{% block navbar%}
    {% include 'navbar.html'%}
{% endblock %}

{% block styles %}
    {{super()}}
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Josefin+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
        crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/index.css">
    <link rel="shortcut icon" href="../static/images/compose.png" type="image/x-icon">

    <style>
        .landing {
    background-image: url("ww.jpg");
    background-position: center;
    background-size: cover;
    background-repeat: no-repeat;
    height: 630px;
    width: 100%;
    
}
    </style>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}


{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="../static/css/index.css">
{% endblock %}


{% block content%}
    <div class="landing">

    </div>
    <div class="main">
        <h1 class="title text-center display-4">Blog Posts</h1>
        <div class="row">
            <div class="posts col-sm-9">
                <div class="container px-auto">
                    {% for post in posts %}
                    <div class="post-card mb-5 text-center">
                        <div class="img-container">
                        <img class="text-center img-responsive" src="{{url_for('static', filename=post.image)}}" alt="" height="600px"
                            width="750px">
                        </div>
                        <h2>{{post.title}}</h2>
                        <h3><em>By {{post.user.full_name}} | {{post.time[0:10]}} at {{post.time[11:16]}}</em></h3>
                        <div class="content">
                            <p>{{post.content[0:200] + "..."}}</p>
                        </div>
                        <div class="links">
                            <a href="{{url_for('main.post_page',id = post.id)}}" class="btn btn-info">Read More</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-sm-2" style="overflow-y: hidden; margin-top: 5px">
                {{wtf.quick_form(form)}}
            </div>
    </div>

{% endblock %}

app/templates/logged.html
{{current_user.username}} is logged in

app/templates/navbar.html
<div style="border-radius: 0;z-index:1;" class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">BLOG</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated%}
                <li><a href="{{url_for('main.add_post')}}">Add Post</a></li>
                <li><a href="{{url_for('main.profile', id = current_user.id)}}">{{current_user.username}}</a></li>
                <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app/templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}

{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="../static/css/post.css">
{% endblock %}

{% block content%}
<h1 class="text-center">{{post.title}}</h1>
    <div class="container content">
        <div class="post-card text-center">
            <div class="img-container">
                <img class="text-center img-responsive" src="{{url_for('static', filename=post.image)}}" alt="" height="600px"
                    width="750px">
            </div>
            <h2>{{post.title}}</h2>
            <h3><em>By {{post.user.full_name}} | {{post.time[0:10]}} at {{post.time[11:16]}}</em></h3>
            <div>
                <p>{{post.content}}</p>
            </div>
        </div>
        <div class="row comment-row">
            <div class="comment-card col-sm-4">
                <h3>Leave a Comment</h3>
                {{wtf.quick_form(form)}}
            </div>
            <div class="comments-card col-sm-6">
                <h3>Comments</h3>
                {% if comments %}
                {% for comment in comments%}
                <p><strong>{{comment.name}}</strong>: {{comment.content}} {% if current_user.is_authenticated %}<a href="{{url_for('main.delete_comment', id = comment.id)}}"><i class="fas fa-trash-alt"></i></a>{% endif %}</p>
                {% endfor%}
                {% else %}
                <p>There are no comments</p>
                {% endif %}
            </div>
        </div>

    </div>
{% endblock%}

app/templates/profile.html
{% extends "base.html" %}

{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="../static/css/index.css">
{% endblock %}


{% block content %}
<div class="container">
    <h1>{{current_user.name | upper}}</h1>
    <div class="row">
        <div class="col-sm-12 col-md-5 col-lg-5">
            {% if user.image %}
            <div class="img-container">
                <img src="{{url_for('static', filename = user.image)}}" class="img-thumbnail profile-pic">
            </div>
            {% else %}
            <p>{{user.full_name}} has no image</p>
            {% endif %}
        </div>
        <div class="col-sm-12 col-md-5 col-lg-5">
            <p>BIO: {{current_user.bio}}</p>
            <a href="{{url_for('main.update_profile',user_id = current_user.id)}}"><button class="btn bio-btn">Edit Profile</button></a>
        </div>
    </div>
    <hr>
    <div class="">
        <h3 class="text-center">My Posts</h3>
        <div class="my-posts">
            {% if posts %}
            {% for post in posts %}
            <div class="post-card mb-5 text-center">
                <div class="img-container">
                    <img class="text-center img-responsive" src="{{url_for('static', filename=post.image)}}" alt="" height="600px"
                        width="750px">
                </div>
                <h2>{{post.title}}</h2>
                <h3><em>By {{post.user.full_name}} | {{post.time[0:10]}} at {{post.time[11:16]}}</em></h3>
                <div class="content">
                    <p>{{post.content[0:200] + "..."}}</p>
                </div>
                <div class="links">
                    <a href="{{url_for('main.post_page',id = post.id)}}" class="btn btn-info">Read More</a>
                    {% if current_user.is_authenticated%}
                    <a href="{{url_for('main.delete',id=post.id)}}" class="btn btn-danger">Delete</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h2>You have no pitches</h2>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/update_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock%}

{% block content%}
<div class="container">
    <div class="row">
        <div class="col-xs-4">
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-xs-4">
            <p>Update Profile Photo</p>
            <form action="{{url_for('main.update_pic',user_id = current_user.id)}}" method="post" enctype="multipart/form-data">
                <input type="file" name="profile-pic" class="form-control" required>
                <div class="btn-container m-4">
                    <input type="submit" value="Upload Photo" class="btn bio-btn">
                </div>
            </form>
        </div>
    </div>
    {% endblock %}